# Generated by Django 5.2.3 on 2025-06-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='technology name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('website', models.URLField(blank=True, null=True, verbose_name='official website')),
                ('logo', models.ImageField(blank=True, height_field='Upload the logo of the technology.', null=True, upload_to='technology_logos/', verbose_name='logo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'technology',
                'verbose_name_plural': 'technologies',
                'ordering': ['name'],
            },
        ),
    ]
