# Generated by Django 5.2.3 on 2025-07-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='logo_height',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='logo',
            field=models.ImageField(blank=True, height_field='logo_height', null=True, upload_to='technology_logos/', verbose_name='logo'),
        ),
    ]
