# Generated by Django 5.2.3 on 2025-06-29 15:29

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='Enter a valid email address. This will be used to log in.', max_length=254, unique=True, verbose_name='email address')),
                ('email_verified', models.BooleanField(default=False, help_text='Indicates whether the user has verified their email address.', verbose_name='email verified')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, help_text='Optional: A short tagline or headline summarizing your professional identity.', verbose_name='headline')),
                ('bio', models.TextField(blank=True, help_text='Optional: Write a short bio to display on your profile.', verbose_name='biography')),
                ('date_of_birth', models.DateField(blank=True, help_text='Optional: Your birth date.', null=True, verbose_name='date of birth')),
                ('city', models.CharField(blank=True, help_text='Your city of residence.', max_length=100, verbose_name='city')),
                ('country', django_countries.fields.CountryField(blank=True, help_text='Your current country of residence.', max_length=2, verbose_name='country of residence')),
                ('profile_picture', models.ImageField(blank=True, help_text='Optional: Upload a profile image.', null=True, upload_to='profile_pictures/', verbose_name='profile picture')),
                ('personal_website', models.URLField(blank=True, help_text='Optional: Your personal/portfolio website.', null=True, verbose_name='personal website')),
                ('linkedin', models.URLField(blank=True, help_text='Optional: Your LinkedIn profile.', null=True, verbose_name='LinkedIn')),
                ('twitter', models.URLField(blank=True, help_text='Optional: You Twitter profile.', null=True, verbose_name='Twitter')),
                ('github', models.URLField(blank=True, help_text='Optional: Your GitHub profile.', null=True, verbose_name='GitHub')),
                ('gitlab', models.URLField(blank=True, help_text='Optional: Your GitLab profile.', null=True, verbose_name='GitLab')),
                ('contact_email', models.EmailField(blank=True, help_text='Optional: Public email for professional contacts.', max_length=254, null=True, verbose_name='contact email')),
                ('languages', models.CharField(blank=True, help_text='Optional: Languages you speak (e.g., English, Spanish).', max_length=255, verbose_name='languages')),
                ('tech_stack', models.ManyToManyField(blank=True, help_text='Your tech stack.', to='technologies.technology')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
