# Generated by Django 5.2.3 on 2025-07-09 13:13

from django.db import migrations, models
from django.utils.translation import gettext_lazy as _


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='email_verified',
            new_name='is_verified',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(
                _('user verified'),
                default=False,
                help_text=_('Indicates whether the user is verified. Required for user to create content.'),
            )
        )
    ]
