# Generated by Django 5.2.3 on 2025-06-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('common', '0002_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, help_text='Your city of residence.', max_length=100, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Optional: Public email for professional contacts.', max_length=254, null=True, verbose_name='contact email'),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Optional: Your birth date.', null=True, verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True, help_text='Optional: Your GitHub profile.', null=True, verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gitlab',
            field=models.URLField(blank=True, help_text='Optional: Your GitLab profile.', null=True, verbose_name='GitLab'),
        ),
        migrations.AddField(
            model_name='profile',
            name='headline',
            field=models.CharField(blank=True, help_text='Optional: A short tagline or headline summarizing your professional identity.', verbose_name='headline'),
        ),
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.CharField(blank=True, help_text='Optional: Languages you speak (e.g., English, Spanish).', max_length=255, verbose_name='languages'),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Optional: Your LinkedIn profile.', null=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='profile',
            name='personal_website',
            field=models.URLField(blank=True, help_text='Optional: Your personal/portfolio website.', null=True, verbose_name='personal website'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tech_stack',
            field=models.ManyToManyField(blank=True, help_text='Your tech stack.', to='common.technology'),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.URLField(blank=True, help_text='Optional: You Twitter profile.', null=True, verbose_name='Twitter'),
        ),
    ]
