# Generated by Django 5.2.3 on 2025-07-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_customuser_email_verified_to_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Write a short bio to display on your profile. Required for verification (min 200 chars).', null=True, verbose_name='biography'),
        ),
    ]
