# Generated by Django 5.2.3 on 2025-07-22 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='News article category.', max_length=80, verbose_name='Category name')),
                ('slug', models.SlugField(help_text='Slug if needed for category modification.', max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Description of the category. Optional.', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'News Category',
                'verbose_name_plural': 'News Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the article source.', max_length=100, verbose_name='Source name')),
                ('base_url', models.URLField(help_text='URL of the article source.', verbose_name='Source URL')),
                ('scrape_allowed', models.BooleanField(default=False, help_text='Indicates whether it is allowed to scrape from that particular source.', verbose_name='Scrape allowed')),
                ('notes', models.TextField(blank=True, help_text='Additional information about the source. Optional.', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'News Source',
                'verbose_name_plural': 'News Sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The main title of the article.', max_length=300, unique=True, verbose_name='Article title')),
                ('slug', models.SlugField(blank=True, help_text='Automatically generated from the title. Used in URL.', max_length=100, unique=True, verbose_name='Slug')),
                ('summary', models.TextField(blank=True, help_text='Short summary for the article.', verbose_name='Summary')),
                ('content', models.TextField(help_text='The actual news content.', verbose_name='Main content')),
                ('cover_image', models.ImageField(blank=True, help_text='Displayed on the top of the news article.', null=True, upload_to='news_covers/', verbose_name='Cover image')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the article was created.', verbose_name='Created at')),
                ('publication_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', help_text='Current status of the article.', max_length=30, verbose_name='Publication status')),
                ('published_at', models.DateTimeField(blank=True, help_text='Date and time of publication.', null=True, verbose_name='Published at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of update.', verbose_name='Updated at')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times the article has been viewed.', verbose_name='View count')),
                ('source_name', models.CharField(blank=True, help_text='Name of the original source if this article was scraped or referenced from another website. Not registered.', max_length=200, verbose_name='External source name')),
                ('source_url', models.URLField(blank=True, help_text='URL of the original source if this article was scraped or referenced from another website. Not registered.', null=True, verbose_name='Source URL')),
                ('authors', models.ManyToManyField(blank=True, help_text='Users credited as authors.', related_name='news_articles', to=settings.AUTH_USER_MODEL, verbose_name='Article authors')),
                ('category', models.ForeignKey(blank=True, help_text='One category per article.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.newscategory', verbose_name='Article category')),
                ('source', models.ForeignKey(blank=True, help_text='Structured reference to a known registered source.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.newssource', verbose_name='Source')),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='news_newsar_slug_342666_idx'), models.Index(fields=['publication_status'], name='news_newsar_publica_ffcc32_idx'), models.Index(fields=['published_at'], name='news_newsar_publish_df29a9_idx')],
            },
        ),
    ]
