# Generated by Django 5.2.3 on 2025-08-01 14:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Automatically generated from the name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'News Category',
                'verbose_name_plural': 'News Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('base_url', models.URLField(verbose_name='Source URL')),
                ('scrape_allowed', models.BooleanField(default=False, verbose_name='Scrape allowed')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'News Source',
                'verbose_name_plural': 'News Sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InternalArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True, verbose_name='News article title')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Automatically generated from the title')),
                ('summary', models.TextField(blank=True, verbose_name='News article summary')),
                ('content', models.TextField(verbose_name='News article content')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='news_covers/', verbose_name='News article poster')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date and time of last update')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date and time of publication')),
                ('publication_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=30, verbose_name='Publication status')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Views count')),
                ('authors', models.ManyToManyField(blank=True, related_name='internal_articles', to=settings.AUTH_USER_MODEL, verbose_name='News article authors')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.newscategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Internal Article',
                'verbose_name_plural': 'Internal Articles',
            },
        ),
        migrations.CreateModel(
            name='ExternalArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True, verbose_name='News article title')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Automatically generated from the title')),
                ('summary', models.TextField(blank=True, verbose_name='News article summary')),
                ('content', models.TextField(verbose_name='News article content')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='news_covers/', verbose_name='News article poster')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date and time of last update')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date and time of publication')),
                ('publication_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=30, verbose_name='Publication status')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Views count')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL to image')),
                ('source_name', models.CharField(blank=True, max_length=200, verbose_name='Source name')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='Source URL')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.newscategory', verbose_name='Category')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_sources', to='news.newssource', verbose_name='Source object')),
            ],
            options={
                'verbose_name': 'External Article',
                'verbose_name_plural': 'External Articles',
            },
        ),
    ]
