# Generated by Django 5.2.3 on 2025-07-26 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('technologies', '0002_technology_logo_height_alter_technology_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Industry name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Company's name.", max_length=80, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, help_text='Automatically generated from the name. Used in the URL.', max_length=100, unique=True, verbose_name='Slug')),
                ('logo', models.ImageField(blank=True, help_text="Company's logo.", null=True, upload_to='company_logo/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, help_text='Summarized information about the company.', verbose_name='Description')),
                ('website', models.URLField(blank=True, help_text="Company's official website.", null=True, verbose_name='Website')),
                ('foundation_date', models.DateField(blank=True, help_text='Date the company was founded.', null=True, verbose_name='Foundation date')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Company Address')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='locations.city', verbose_name='Headquarters City')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headquartered_companies', to='locations.country', verbose_name='Headquarters Country')),
                ('operating_countries', models.ManyToManyField(blank=True, related_name='operating_companies', to='locations.country', verbose_name='Operating Countries')),
                ('tech_stack', models.ManyToManyField(blank=True, help_text='The tech stack company uses for their services.', related_name='companies', to='technologies.technology', verbose_name='Tech stack')),
                ('industries', models.ManyToManyField(blank=True, help_text='Company can cover multiple areas of operation.', related_name='companies', to='companies.industry', verbose_name='Industry')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
    ]
