# Generated by Django 5.2.3 on 2025-07-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('technologies', '0002_technology_logo_height_alter_technology_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industries',
            field=models.ManyToManyField(blank=True, help_text='Company can cover multiple areas of operation.', related_name='companies', to='companies.industry', verbose_name='Industry'),
        ),
        migrations.AlterField(
            model_name='company',
            name='operating_countries',
            field=models.ManyToManyField(blank=True, help_text='Company can have businesses in multiple countries.', related_name='companies_operating', to='companies.location', verbose_name='Countries of operation'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tech_stack',
            field=models.ManyToManyField(blank=True, help_text='The tech stack company uses for their services.', related_name='companies', to='technologies.technology', verbose_name='Tech stack'),
        ),
    ]
