# Generated by Django 5.2.3 on 2025-08-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_city_remove_company_country_and_more'),
        ('industries', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Industry',
        ),
        migrations.AlterField(
            model_name='company',
            name='industries',
            field=models.ManyToManyField(blank=True, help_text='Company can cover multiple areas of operation.', related_name='companies', to='industries.industry', verbose_name='Industry'),
        ),
    ]
