# Generated by Django 5.2.3 on 2025-06-27 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The main heading for the content', max_length=200, verbose_name='title')),
                ('cover_image', models.ImageField(blank=True, help_text='Displayed at the top of the tutorial or article.', null=True, upload_to='tutorial_covers/', verbose_name='cover image')),
                ('slug', models.SlugField(blank=True, help_text='Automatically generated from the title. Used in the ULR.', max_length=220, unique=True, verbose_name='slug')),
                ('summary', models.TextField(help_text='A short summary shown in listings or previews.', max_length=500, verbose_name='summary')),
                ('content', models.TextField(help_text='Main body of the content. Supports markdown or rich text with code blocks.', verbose_name='content')),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='Not provided', help_text='Select the intended difficulty level for this content.', max_length=20, verbose_name='difficulty')),
                ('estimated_duration', models.PositiveIntegerField(blank=True, help_text='Estimated time to complete/read.', null=True, verbose_name='estimated duration in minutes')),
                ('is_published', models.BooleanField(default=False, help_text='Control whether the content is publicly visible.', verbose_name='is published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('authors', models.ManyToManyField(help_text='Users credited as authors.', related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='authors')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags for categorizing content.', related_name='%(class)ss', to='common.tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'tutorial',
                'verbose_name_plural': 'tutorials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TutorialCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.tutorial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tutorial completion',
                'verbose_name_plural': 'tutorial completions',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The main heading for the content', max_length=200, verbose_name='title')),
                ('cover_image', models.ImageField(blank=True, help_text='Displayed at the top of the tutorial or article.', null=True, upload_to='tutorial_covers/', verbose_name='cover image')),
                ('slug', models.SlugField(blank=True, help_text='Automatically generated from the title. Used in the ULR.', max_length=220, unique=True, verbose_name='slug')),
                ('summary', models.TextField(help_text='A short summary shown in listings or previews.', max_length=500, verbose_name='summary')),
                ('content', models.TextField(help_text='Main body of the content. Supports markdown or rich text with code blocks.', verbose_name='content')),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='Not provided', help_text='Select the intended difficulty level for this content.', max_length=20, verbose_name='difficulty')),
                ('estimated_duration', models.PositiveIntegerField(blank=True, help_text='Estimated time to complete/read.', null=True, verbose_name='estimated duration in minutes')),
                ('is_published', models.BooleanField(default=False, help_text='Control whether the content is publicly visible.', verbose_name='is published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('authors', models.ManyToManyField(help_text='Users credited as authors.', related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='authors')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags for categorizing content.', related_name='%(class)ss', to='common.tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='learning_ar_slug_6b1f6e_idx'), models.Index(fields=['created_at'], name='learning_ar_created_241985_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tutorial',
            index=models.Index(fields=['slug'], name='learning_tu_slug_28bee4_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorial',
            index=models.Index(fields=['created_at'], name='learning_tu_created_ef3eec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tutorialcompletion',
            unique_together={('user', 'tutorial')},
        ),
    ]
