# Generated by Django 5.2.3 on 2025-07-08 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_article_views_tutorial_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={'ordering': ['-created_at'], 'permissions': [('can_publish_tutorials', 'Can publish tutorials'), ('can_edit_others_tutorials', "Can edit others' tutorials")], 'verbose_name': 'tutorial', 'verbose_name_plural': 'tutorials'},
        ),
    ]
