# Generated by Django 5.2.3 on 2025-07-17 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_category_article_categories_tutorial_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not-started', 'Not Started'), ('in-progress', 'In Progress'), ('completed', 'Completed')], default='not-started', max_length=30)),
                ('bookmarked', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='learning.tutorial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tutorial progress',
                'verbose_name_plural': 'tutorial progress records',
                'unique_together': {('user', 'tutorial')},
            },
        ),
        migrations.DeleteModel(
            name='TutorialCompletion',
        ),
    ]
