# Generated by Django 5.2.3 on 2025-07-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_tutorialprogress_delete_tutorialcompletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='difficulty',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', help_text='Select the intended difficulty level for this content.', max_length=20, verbose_name='difficulty'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='difficulty',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', help_text='Select the intended difficulty level for this content.', max_length=20, verbose_name='difficulty'),
        ),
    ]
