# Generated by Django 5.2.3 on 2025-07-19 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_alter_article_difficulty_alter_tutorial_difficulty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tutorialprogress',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='tutorialprogress',
            constraint=models.UniqueConstraint(fields=('user', 'tutorial'), name='unique_user_tutorial_progress'),
        ),
    ]
