# Generated by Django 5.2.3 on 2025-07-28 21:15

import apps.job_listings.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_remove_company_city_remove_company_country_and_more'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The main heading of the job post.', max_length=150, verbose_name='Job post title')),
                ('slug', models.SlugField(blank=True, help_text='Automatically generated from the title.', max_length=150, unique=True, verbose_name='Slug')),
                ('company_name_raw', models.CharField(blank=True, help_text='Used when the company is not registered. Will be ignored if a registered company is selected.', max_length=150, verbose_name='Company Name (Text)')),
                ('job_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('self_employed', 'Self-employed'), ('contract', 'Contract'), ('internship', 'Internship'), ('apprenticeship', 'Apprenticeship'), ('freelance', 'Freelance'), ('volunteer', 'Volunteer')], default='full_time', help_text='Job contract type.', max_length=30, verbose_name='Job Type')),
                ('employment_mode', models.CharField(choices=[('on_site', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='on_site', help_text='Defining the place of work.', max_length=30, verbose_name='Employment Mode')),
                ('experience_level', models.CharField(choices=[('intern', 'Intern'), ('entry', 'Entry Level'), ('junior', 'Junior'), ('mid', 'Mid-Level'), ('senior', 'Senior'), ('lead', 'Lead'), ('principal', 'Principal'), ('architect', 'Architect'), ('manager', 'Manager'), ('director', 'Director'), ('executive', 'Executive / CTO')], default='entry', help_text='Required experience for the position.', max_length=20, verbose_name='Experience Level')),
                ('description', models.TextField(help_text='Summary about the position.', verbose_name='Job Description')),
                ('responsibilities', models.TextField(blank=True, help_text="What will employee's responsibilities be at work.", verbose_name='Responsibilities')),
                ('requirements', models.TextField(blank=True, help_text='Requirements in terms of knowledge and skillset.', verbose_name='Requirements')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, help_text='Lowest expected salary (optional).', max_digits=10, null=True, verbose_name='Minimum Salary')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, help_text='Highest expected salary (optional).', max_digits=10, null=True, verbose_name='Maximum Salary')),
                ('currency', models.CharField(choices=[('GBP', 'GBP'), ('USD', 'USD'), ('EUR', 'EUR'), ('AUD', 'AUD'), ('CAD', 'CAD'), ('NZD', 'NZD'), ('ZAR', 'ZAR'), ('HKD', 'HKD')], default='GBP', help_text='Some contracts can come from abroad.', max_length=5, verbose_name='Currency')),
                ('is_active', models.BooleanField(default=False, help_text='Shows whether the job is still available.', verbose_name='Job Visibility')),
                ('published_at', models.DateTimeField(auto_now_add=True, help_text='Automatically published when meets the conditions in the other fields.', verbose_name='Published At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the job post is updated.', verbose_name='Updated At')),
                ('source', models.CharField(blank=True, help_text='If job was imported, specify the API or service name, e.g., Indeed, LinkedIn.', max_length=150, verbose_name='External Source')),
                ('external_reference', models.CharField(blank=True, help_text='Unique job ID from external API source (if applicable). Useful for updates and sync.', max_length=200, verbose_name='External Reference ID')),
                ('company', models.ForeignKey(blank=True, help_text='Link to a registered company in the database (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posts', to='companies.company', verbose_name='Registered Company')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this job post. Null if imported from an external source.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posts_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('location', models.ForeignKey(help_text="Job's location.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Job Post',
                'verbose_name_plural': 'Job Posts',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Used to confirm application or for employer contact.', max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('message', models.TextField(blank=True, help_text='Optional message or motivation.', verbose_name='Cover Message')),
                ('cover_letter', models.FileField(help_text='Optional letter or motivation. If you preffer sending a file.', upload_to='applications/letters/', validators=[apps.job_listings.validators.FileExtensionValidator(allowed_extensions=['.pdf', '.doc', '.docx']), apps.job_listings.validators.FileSizeValidator(max_mb=5)], verbose_name='Cover Letter')),
                ('cv', models.FileField(help_text='Upload your CV in PDF or DOCX format.', upload_to='applications/cvs/', validators=[apps.job_listings.validators.FileExtensionValidator(allowed_extensions=['.pdf', '.doc', '.docx']), apps.job_listings.validators.FileSizeValidator(max_mb=5)], verbose_name='CV / Résumé')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submitted At')),
                ('user', models.ForeignKey(blank=True, help_text='If the applicant is a registered user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_applications', to=settings.AUTH_USER_MODEL, verbose_name='User (optional)')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='job_listings.jobpost', verbose_name='Job Post')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPostUpdateHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_summary', models.TextField(blank=True, help_text='Optional notes about what was changed.', verbose_name='Edit Summary')),
                ('edited_at', models.DateTimeField(auto_now_add=True, verbose_name='Edited At')),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Edited By')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='job_listings.jobpost', verbose_name='Job Post')),
            ],
            options={
                'verbose_name': 'Job Post Edit History',
                'verbose_name_plural': 'Job Post Edit Histories',
                'ordering': ['-edited_at'],
            },
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['slug'], name='job_listing_slug_d4dab8_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['is_active'], name='job_listing_is_acti_246a60_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['published_at'], name='job_listing_publish_3acde2_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobpost',
            constraint=models.CheckConstraint(condition=models.Q(('salary_min__lte', models.F('salary_max'))), name='salary_min_lte_max'),
        ),
        migrations.AddConstraint(
            model_name='jobpost',
            constraint=models.UniqueConstraint(condition=models.Q(('external_reference__isnull', False), ('source__isnull', False)), fields=('source', 'external_reference'), name='unique_external_job'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job'], name='job_listing_job_id_e4994e_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['user'], name='job_listing_user_id_d451e1_idx'),
        ),
    ]
