# Generated by Django 5.2.3 on 2025-07-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Shows whether the job is still available.', verbose_name='Job Visibility'),
        ),
    ]
