# Generated by Django 5.2.3 on 2025-07-29 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_listings', '0002_alter_jobpost_is_active'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobpost',
            name='unique_external_job',
        ),
    ]
