# Generated by Django 5.2.3 on 2025-06-29 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='forum.forumcategory')),
            ],
            options={
                'verbose_name': 'forum category',
                'verbose_name_plural': 'forum categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The main heading for the post.', max_length=255, verbose_name='post title')),
                ('slug', models.SlugField(blank=True, help_text='Automatically generated from the title. Used in URL.', max_length=255, unique=True, verbose_name='slug')),
                ('content', models.TextField(help_text='Main body of the post.', verbose_name='content')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='pinned')),
                ('is_closed', models.BooleanField(default=False, verbose_name='closed')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='views')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='forum.forumcategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'forum post',
                'verbose_name_plural': 'forum posts',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
