# Generated by Django 5.2.3 on 2025-07-03 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumpost',
            options={'ordering': ['-is_pinned', '-created_at'], 'permissions': [('can_publish_posts', 'Can publish posts'), ('can_pin_posts', 'Can pin posts'), ('can_close_posts', 'Can close posts'), ('can_edit_others_posts', "Can edit others' posts")], 'verbose_name': 'forum post', 'verbose_name_plural': 'forum posts'},
        ),
    ]
