# Generated by Django 5.2.3 on 2025-07-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_forumpost_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='published'),
        ),
    ]
